name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
      - master

env:
  ACR_NAME: myacrname       # apni ACR ka naam yahan daalo (without .azurecr.io)
  IMAGE_NAME: myflaskapp    # image ka naam
  RESOURCE_GROUP: myrg      # terraform resource group name
  LOCATION: eastus

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name $ACR_NAME

    - name: Build Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

    - name: Push Docker Image to ACR
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="image_tag=${{ github.sha }}" \
          -var="resource_group_name=$RESOURCE_GROUP" \
          -var="acr_name=$ACR_NAME" \
          -var="image_name=$IMAGE_NAME" \
          -var="location=$LOCATION"
      working-directory: ./terraform
